# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2baabf70d26d2fdd248add031cba309118da7c7bdda5e6aefc722ea8fd9e28b329933b4f20b469a00775d87f9967e06500ac8a1a8b47067b25e79ca1f5324a23

test:
  secret_key_base: 5481be83a0cda30cbd7d74b4c69e1eeeebdeaac1d63a42b7248577ebec1e73959e3eaa6e2ea410de4a6e284ae89ec2bb76f2808638b5c55cf8e3b8514d8dd765

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
